In [2]:
import pandas as pd
import numpy as np
import itertools

In [41]:
def stratified_shuffle(df, stratify_cols, random_cols, random_state=None):
    df = df.sort_values(stratify_cols+random_cols).reset_index(drop=True)
    
    unique_r = df[random_cols].drop_duplicates()
    n_unique_r = len(unique_r)
    unique_g = df[stratify_cols].drop_duplicates()
    n_unique_g = len(unique_g)

    new_df = pd.DataFrame()
    for g in range(n_unique_g):
        new_df = pd.concat([new_df, df[g*n_unique_r:(g+1)*n_unique_r].sample(frac=1).reset_index(drop=True)], ignore_index=True)
    df = new_df
    new_df = pd.DataFrame()
    for r in range(n_unique_r):
        new_df = pd.concat([new_df, df[r::n_unique_r]], ignore_index=True)
    df = new_df
    new_df = pd.DataFrame()
    for r in range(n_unique_r):
        new_df = pd.concat([new_df, df[r*n_unique_g:(r+1)*n_unique_g].sample(frac=1).reset_index(drop=True)], ignore_index=True)
    df = new_df
    return df

In [42]:
stratified_shuffle(df, ['group'], ['replication'], random_state=42)

    group  replication
0       0            8
1       2            6
2       3            9
3       1            9
4       3            1
5       2            8
6       1            7
7       0            6
8       0            9
9       1            8
10      2            5
11      3            4
12      3            5
13      1            5
14      2            4
15      0            1
16      0            7
17      3            6
18      1            0
19      2            0
20      3            0
21      2            1
22      0            0
23      1            3
24      3            7
25      0            5
26      1            6
27      2            7
28      3            3
29      2            3
30      0            2
31      1            2
32      2            9
33      0            4
34      1            4
35      3            8
36      0            3
37      1            1
38      3            2
39      2            2

In [39]:
group = np.arange(4)
replication = np.arange(10)
df = pd.DataFrame(list(itertools.product(group, replication)), columns=['group', 'replication'])
df = df.sort_values(['group', 'replication']).reset_index(drop=True)

In [ ]:
unique_replications = df['replication'].unique()
n_unique_replications = len(unique_replications)
unique_groups = df['group'].unique()
n_unique_groups = len(unique_groups)

new_df = pd.DataFrame()
for g in range(n_unique_groups):
    new_df = pd.concat([new_df, df[g*n_unique_replications:(g+1)*n_unique_replications].sample(frac=1).reset_index(drop=True)], ignore_index=True)
df = new_df
new_df = pd.DataFrame()
for r in range(n_unique_replications):
    new_df = pd.concat([new_df, df[r::n_unique_replications]], ignore_index=True)
df = new_df
new_df = pd.DataFrame()
for r in range(n_unique_replications):
    new_df = pd.concat([new_df, df[r*n_unique_groups:(r+1)*n_unique_groups].sample(frac=1).reset_index(drop=True)], ignore_index=True)
df = new_df

In [36]:
df

    group  replication
0       3            3
1       2            2
2       1            5
3       0            1
4       0            3
5       3            9
6       1            4
7       2            6
8       2            7
9       1            9
10      3            4
11      0            6
12      2            8
13      1            8
14      0            7
15      3            2
16      2            3
17      3            5
18      0            9
19      1            7
20      0            4
21      3            0
22      2            1
23      1            2
24      2            9
25      3            8
26      0            2
27      1            0
28      3            6
29      0            5
30      2            5
31      1            1
32      2            4
33      3            7
34      0            0
35      1            6
36      3            1
37      0            8
38      2            0
39      1            3

In [ ]:
unique_replications = tasks_df['replication'].unique()
n_replications = len(unique_replications)
unique_tasks_df = tasks_df.drop_duplicates(subset=['f', 'sigma', 'implementation', 'penalised', 'builder'])
n_unique_tasks = len(unique_tasks_df)
# Randomise replication order within each task
group_cols = ['f', 'sigma', 'implementation', 'penalised', 'builder']
print(tasks_df.columns)
tasks_df = (
    tasks_df.groupby(
        group_cols,
        group_keys=False
    )
    .apply(lambda g: g.sample(frac=1))
    .reset_index(drop=True)
)
print(tasks_df.columns)
# Assign a batch number within each task
tasks_df['batch'] = tasks_df.groupby(group_cols).cumcount()
# Shuffle within each batch
tasks_df = (
    tasks_df.groupby('batch', group_keys=False)
    .apply(lambda g: g.sample(frac=1))
    .reset_index(drop=True)
    .drop(columns='batch')
)
print(tasks_df.head(20))
sys.exit()
# Create balanced batches
batches = []
for i in range(n_replications):
    batches.append(
        tasks_df.groupby(
            ['f','sigma','implementation','penalised','builder'],
            group_keys=False
        )
        .nth(i)
        .sample(frac=1)
    )

tasks_df = pd.concat(batches, ignore_index=True)
print(tasks_df.head(20))
sys.exit()

tasks_df = tasks_df.sample(frac=1, random_state=42).reset_index(drop=True)
tasks_df = tasks_df.sort_values(['f', 'sigma', 'implementation', 'penalised', 'builder']).reset_index(drop=True)
unique_replications = tasks_df['replication'].unique()
n_replications = len(unique_replications)
unique_tasks_df = tasks_df.drop_duplicates(subset=['f', 'sigma', 'implementation', 'penalised', 'builder'])
n_unique_tasks = len(unique_tasks_df)
new_tasks_df = pd.DataFrame()
for i in range(n_replications):
    new_tasks_df = pd.concat([new_tasks_df, tasks_df[i::n_replications]], ignore_index=True)
tasks_df = new_tasks_df
new_tasks_df = pd.DataFrame()
for i in range(n_replications):
    new_tasks_df = pd.concat([new_tasks_df, tasks_df[i*n_unique_tasks:(i+1)*n_unique_tasks].sample(frac=1).reset_index(drop=True)], ignore_index=True)
tasks_df = new_tasks_df
print(tasks_df.head(20))
sys.exit()

unique_replications = tasks_df['replication'].unique()
np.random.shuffle(unique_replications)
print(unique_replications)
n_replications = len(unique_replications)
#tasks_df = tasks_df.sample(frac=1, random_state=42).reset_index(drop=True)
tasks_df = tasks_df.sort_values(['replication', 'f', 'sigma', 'implementation', 'penalised', 'builder']).reset_index(drop=True)
unique_tasks_df = tasks_df.drop_duplicates(subset=['f', 'sigma', 'implementation', 'penalised', 'builder'])
n_unique_tasks = len(unique_tasks_df)
tasks_df['replication'] = list(itertools.chain.from_iterable([[r]*n_unique_tasks for r in unique_replications]))
new_tasks_df = pd.DataFrame()
for i in range(n_replications):
    new_tasks_df = pd.concat([new_tasks_df, tasks_df[i*n_unique_tasks:(i+1)*n_unique_tasks].sample(frac=1, random_state=42).reset_index(drop=True)], ignore_index=True)
tasks_df = new_tasks_df
#new_tasks_df = pd.DataFrame()
#for i in range(n_replications):
    #new_tasks_df = pd.concat([new_tasks_df, tasks_df[i::n_replications]], ignore_index=True)
#tasks_df = new_tasks_df
print(tasks_df.head(20))
sys.exit()